services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: java-dev
    volumes:
      - .:/workspace
  cs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: cs-dev
    volumes:
      - .:/workspace
